name: uni_pluse
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  socket_io_client: ^2.0.3
  easy_localization: ^3.0.7+1
  font_awesome_flutter: ^10.5.0
  fl_chart: ^0.66.0
  table_calendar: ^3.0.9
  url_launcher: ^6.1.7
  url_launcher_linux: ^2.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar1.png
    - assets/images/avatar2.png
    - assets/images/avatar3.png
    - assets/images/inicio.png
    - assets/images/logo.png
    - assets/langs/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
